### ISSUE TITLE
Estilizado

### ISSUE THREAD

**Issue by maxpipoka** [AndresGarva/E-Commerce-React.JS-UNaM#3]
Esta super bien encaminado tu proyecto Andres.
Necesita trabajo fuerte en el estilizado. 
En movil Al entrar a a sección About y darle al botón del menú lateral, aparece por detras del contenido.

Necesita mejorar la estética en general, suavizar los colores o hacerlo mas facil de leer tambien.

Pero funcionalmente esta muy bien.

**Comment by AndresGarva** [comment]
Gracias Martín por tu devolución.

Voy a corregir las imperfecciones en el tema estético.
Y las funcionalidades responsivas.

Me gustaría saber que es para vos el
"Necesita trabajo fuerte de estilizado" para poder resolverlo de manera
óptima.

Otra consulta es de que manera me recomiendas vos el realizar
"Hacerlo más fácil de leer" ya que la página es algo sencillo y fue pensada
directa en un contraste oscuro. Ya que las páginas son más que nada
"personales" y según las pautas originales al dueño de la misma. Como hay
alguien le guste las tonalidades claras, en lo particular los diseños que
he realizado yo en otro tipo de proyecto han sido tonalidades oscuras. Por
eso me gustaría preguntarte, si a vos te gustaría que le cambié la gama de
colores de mí proyecto. Par hacer una reversión completa pero en
tonalidades claras.

Una consulta más y es que me gustaría saber cuál es el puntaje del criterio
de evaluación que tengo en mí proyecto.
Para saber si me quedé muy lejos del aprobado. Ya que el proyecto en si
cumple con todas las funcionalidades y cumple con 8 de los 10 puntos claves.
Gracias

Atte: Andrés Garvagnate
